installType: upstream
rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
imagestream: false
writeStatusName: '""'
writePackageServerStatusName: ""
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:4cbf3c7fe8cded498d43a41e68ee32daadddddfc46735535eac4bd8db80d4789
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:4cbf3c7fe8cded498d43a41e68ee32daadddddfc46735535eac4bd8db80d4789
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 2
  maxUnavailable: 1
  maxSurge: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:4cbf3c7fe8cded498d43a41e68ee32daadddddfc46735535eac4bd8db80d4789
    pullPolicy: Always
  service:
    internalPort: 5443
  securityContext:
    runAsUser: 1000
catalog_sources:
  - rh-operators
